# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m 

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: mvn -s .circleci/.circleci.settings.xml clean package -DskipTests
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      
      - run: mkdir -p /tmp/workspace/ && cp -r target /tmp/workspace
      - run: ls -lart /tmp/workspace/target
      - persist_to_workspace:
          root: /tmp/workspace/target
          paths:
            - ./*
            - ./*.jar          
  test:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m 
    steps:
      - checkout    
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: mvn -s .circleci/.circleci.settings.xml test
      - store_test_results:          
          path: target/surefire-reports      
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}      
  deploy:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m 
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: sed -i "s/BUILDNUMBER/$CIRCLE_BUILD_NUM/g" pom.xml
      - run: mvn -T1.5C -s .circleci/.circleci.settings.xml deploy -DskipTests
  publish:
    machine:
      enabled: true
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: |
          mkdir target
          mv /tmp/workspace/target/*.jar target/product-list-emitter.jar
          TAG=1.1.$CIRCLE_BUILD_NUM
          docker build -t sredna/product-list-emitter:$TAG .
          docker tag sredna/product-list-emitter:$TAG sredna/product-list-emitter:latest
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push sredna/product-list-emitter:$TAG
          docker push sredna/product-list-emitter:latest
workflows:
  version: 2
  full_boat:
    jobs: 
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - master
      - publish:
          requires:
            - test
          filters:
            branches:
              only:
                - master                
